In [3]:
import numpy as np

def npSum():
    a = np.array([0,1,2,3,4])
    b = np.array([9,8,7,6,5])
    c = a**2 + b**3
    return c

print(npSum())

[729 513 347 225 141]


In [6]:
a = np.array([[0,1,2,3,4],[9,8,7,6,5]])

In [9]:
a.ndim

2

In [10]:
a.shape

(2, 5)

In [11]:
a.size

10

In [12]:
a.dtype

dtype('int64')

In [13]:
a.itemsize

8

ndarray数组的创建方法
1. 从Python中的列表、元组等类型创建ndarray数组
2. 

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.zeros((3,6),dtype=np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
x = np.ones((2,3,4))

In [26]:
x.shape

(2, 3, 4)

In [ ]:
np.ones_like(a)

In [29]:
a = np.linspace(1,10,4)

In [30]:
b = np.linspace(1,10,4,endpoint=False)

In [33]:
np.concatenate((a,b))

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

|方法|说明|
|:--:|:--:|
|.reshape(shape)| 不改变数组元素，返回一个shape形状的数组，原数组不变|
|.resize(shape) |与.reshape()功能一致，但修改原数组|
|.swapaxes(ax1,ax2)| 将数组n个维度中两个维度进行调换|
|.flatten()| 对数组进行降维，返回折叠后的一维数组，原数组不变|

a.astype(new_type) 数组类型的变换
astype()方法一定会创建新的数组（原始数据的一个拷贝），即使两个类型一致

ls = a.tolist()   ndarray数组向列表的转换


In [34]:
a = np.full((2,3,4),25,dtype=np.int32)
a

array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]]], dtype=int32)

In [36]:
a.tolist()

[[[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]],
 [[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]]]

## 数组的索引和切片
一维数组的索引和切片：与Python的列表类似
多维数组的索引：

In [39]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [38]:
a[1,2,3]

23

In [40]:
a[:,1,-3]

array([ 5, 17])

## ndarray数组的运算
数组与标量之间的运算作用于数组的每一个元素

## NumPy一元函数
对ndarray中的数据执行元素级运算的函数

|函数|说明|
|:--:|:--:|
|np.abs(x) np.fabs(x)| 计算数组各元素的绝对值|
|np.sqrt(x) |计算数组各元素的平方根|
|np.square(x)| 计算数组各元素的平方|
|np.log(x) np.log10(x) np.log2(x)| 计算数组各元素的自然对数、10底对数和2底对数|
|np.ceil(x) np.floor(x)| 计算数组各元素的ceiling值或floor值|
|np.rint(x) |计算数组各元素的四舍五入值|
|np.modf(x)| 将数组各元素的小数和整数部分以两个独立数组形式返回|
|np.cos(x) np.cosh(x) np.sin(x) np.sinh(x) np.tan(x) np.tanh(x)|计算数组各元素的普通型和双曲型三角函数|
|np.exp(x)| 计算数组各元素的指数值|
|np.sign(x)| 计算数组各元素的符号值，1(+), 0, ‐1(‐)|

## NumPy二元函数
|函数|说明|
|:--:|:--:|
|+ ‐ * / ** |两个数组各元素进行对应运算|
|np.maximum(x,y) np.fmax()np.minimum(x,y) np.fmin()| 元素级的最大值/最小值计算|
|np.mod(x,y)| 元素级的模运算|
|np.copysign(x,y)| 将数组y中各元素值的符号赋值给数组x对应元素|
|> < >= <= == != |算术比较，产生布尔型数组|