In [2]:
from tvtk.tools import tvtk_doc
tvtk_doc.main()

In [4]:
from tvtk.api import tvtk
s = tvtk.CubeSource(x_length=1.0,y_length=2.0,z_length=3.0)
print(s)

vtkCubeSource (0000021FE09B1530)
  Debug: Off
  Modified Time: 1186979
  Reference Count: 2
  Registered Events: 
    Registered Observers:
      vtkObserver (0000021FE099D010)
        Event: 33
        EventName: ModifiedEvent
        Command: 0000021FE4AA3960
        Priority: 0
        Tag: 1
  Executive: 0000021FE13619E0
  ErrorCode: No error
  Information: 0000021FE0EDF4D0
  AbortExecute: Off
  Progress: 0
  Progress Text: (None)
  X Length: 1
  Y Length: 2
  Z Length: 3
  Center: (0, 0, 0)
  Output Points Precision: 0




[TVTK帮助资源](http://www.vtk.org/doc/nightly/html/annotated.html
)  

1. TVTK库中的类名去除了前缀vtk
2. 函数名按照Python的惯例,采用下划线连接单词
  如`AddItem`->`add_item`
3. VTK对象的方法在TVTK中用Trait属性替代
    1. m.SetInputConnnection(c.GetOutputPort()) #VTK
    2. m.input_connection(c.output_port)  #TVTK


In [7]:
s.y_length  ##属性

2.0

In [8]:
s.center

array([0., 0., 0.])

In [9]:
s.output_points_precision

0

![](http://oss.flameszj.top/img/20200914185221.png)
![](http://oss.flameszj.top/img/20200914185236.png)
## 创建数据源

In [10]:

S = tvtk.ConeSource(height=3.0,radius=1.0,resolution=36)

In [11]:
S.radius

1.0

In [12]:
S.resolution

36

In [13]:
S.center

array([0., 0., 0.])

In [15]:
print(S)

vtkConeSource (0000021FE086B790)
  Debug: Off
  Modified Time: 1187013
  Reference Count: 2
  Registered Events: 
    Registered Observers:
      vtkObserver (0000021FE0683B10)
        Event: 33
        EventName: ModifiedEvent
        Command: 0000021FE4AA2A20
        Priority: 0
        Tag: 1
  Executive: 0000021FE1362520
  ErrorCode: No error
  Information: 0000021FE0EE0240
  AbortExecute: Off
  Progress: 0
  Progress Text: (None)
  Resolution: 36
  Height: 3
  Radius: 1
  Capping: On
  Center: (0, 0, 0)
  Direction: (1, 0, 0)
  Output Points Precision: 0




## 显示数据源

In [19]:
from tvtk.api import tvtk
 
# 创建一个长方体数据源，并且同时设置其长宽高
s = tvtk.CubeSource(x_length=1.0, y_length=2.0, z_length=3.0)
# 使用PolyDataMapper将数据转换为图形数据
m = tvtk.PolyDataMapper(input_connection=s.output_port)
# 创建一个Actor
a = tvtk.Actor(mapper=m)
# 创建一个Renderer，将Actor添加进去
r = tvtk.Renderer(background=(0, 0, 0))
r.add_actor(a)
# 创建一个RenderWindow(窗口)，将Renderer添加进去
w = tvtk.RenderWindow(size=(300,300))
w.add_renderer(r)
# 创建一个RenderWindowInteractor（窗口的交互工具)
i = tvtk.RenderWindowInteractor(render_window=w)
# 开启交互
i.initialize()
i.start()

In [20]:
s.output_port

In [21]:
m.input_connection

## 理解TVTK的管线
1. 可视化管线(Visualization Pipeline):将原始数据加工成图形数据的过程。
2. 图形管线(Graphics Pipeline):图形数据加工为我们所看到的图像的过程。
![](http://oss.flameszj.top/img/20200914190450.png)
![](http://oss.flameszj.top/img/20200914190717.png)

In [22]:
from tvtk.api import tvtk
from tvtk.tools import ivtk
from pyface.api import GUI
 
s = tvtk.CubeSource(x_length=1.0, y_length=2.0, z_length=3.0)
m = tvtk.PolyDataMapper(input_connection=s.output_port)
a = tvtk.Actor(mapper=m)
 
#创建一个带Crust（Python Shell）的窗口
gui = GUI()
win = ivtk.IVTKWithCrustAndBrowser()
win.open()
win.scene.add_actor(a)
 
#开始界面消息循环
gui.start_event_loop()

In [25]:
from tvtk.api import tvtk
from tvtk.tools import ivtk
from pyface.api import GUI
 
s = tvtk.CubeSource(x_length=1.0, y_length=2.0, z_length=3.0)
m = tvtk.PolyDataMapper(input_connection=s.output_port)
a = tvtk.Actor(mapper=m)
 
#创建一个带Crust（Python Shell）的窗口
gui = GUI()
win = ivtk.IVTKWithCrustAndBrowser()
win.open()
win.scene.add_actor(a)
     
#修正窗口错误
dialog = win.control.centralWidget().widget(0).widget(0)
from pyface.qt import QtCore
dialog.setWindowFlags(QtCore.Qt.WindowFlags(0x00000000))
dialog.show()
 
gui.start_event_loop()

In [ ]:
from tvtk.api import tvtk
 
def ivtk_scene(actors):
    from tvtk.tools import ivtk
    #创建一个带Crust（Python Shell）的窗口
    win = ivtk.IVTKWithCrustAndBrowser()
    win.open()
    win.scene.add_actor(actors)
    #修正窗口错误
    dialog = win.control.centralWidget().widget(0).widget(0)
    from pyface.qt import QtCore
    dialog.setWindowFlags(QtCore.Qt.WindowFlags(0x00000000))
    dialog.show()
    return win
 
def event_loop():
    from pyface.api import GUI
    gui = GUI()
    gui.start_event_loop()
 
s = tvtk.CubeSource(x_length=1.0, y_length=2.0, z_length=3.0)
m = tvtk.PolyDataMapper(input_connection=s.output_port)
a = tvtk.Actor(mapper=m)
win = ivtk_scene(a)
win.scene.isometric_view()
event_loop()

## 数据集
1. ImageData表示二维或三维图像的数据结构。
2. RectilinearGrid:间距不均匀的网格,所有点都在正交的网格上。
3. StructuredGrid:创建任意形状的网格,需要指定点的坐标。
4. PolyData:由一系列的点、点之间的联系以及由点构成的多边形组成。

![](http://oss.flameszj.top/img/20200914193248.png)

In [28]:
from tvtk.api import tvtk
img = tvtk.ImageData(spacing=(1,1,1),origin=(1,2,3),dimensions=(3,4,5))
img.get_point(0)

(1.0, 2.0, 3.0)

In [29]:
for n in range(6):
    print('%.1f,%.1f,%.1f'%img.get_point(n))

1.0,2.0,3.0
2.0,2.0,3.0
1.0,3.0,3.0
2.0,3.0,3.0
1.0,4.0,3.0
2.0,4.0,3.0


In [30]:
from tvtk.api import tvtk
import numpy as np
 
x = np.array([0,3,9,15])
y = np.array([0,1,5])
z = np.array([0,2,3])
r = tvtk.RectilinearGrid()
r.x_coordinates = x
r.y_coordinates = y
r.z_coordinates = z
r.dimensions = len(x),len(y),len(z)

In [31]:
for n in range(6):
    print('%.1f,%.1f,%.1f'%r.get_point(n))

0.0,0.0,0.0
3.0,0.0,0.0
9.0,0.0,0.0
15.0,0.0,0.0
0.0,1.0,0.0
3.0,1.0,0.0


##  TVTK数据加载
![](http://oss.flameszj.top/img/20200914193614.png)
![](http://oss.flameszj.top/img/20200914193633.png)


### tvtk模型读取

In [33]:
from tvtk.api import tvtk
from tvtkfunc import ivtk_scene,event_loop ## 需要外部tvtkfunc.py文件
 
s = tvtk.STLReader(file_name = "temp/tvtk/python.stl")
m = tvtk.PolyDataMapper(input_connection = s.output_port)
a = tvtk.Actor(mapper = m)
 
win = ivtk_scene(a)
win.scene.isometric_view()
event_loop()

### MultiBlock模型读取

In [35]:
from tvtk.api import tvtk
 
def read_data():# 读入数据
    plot3d = tvtk.MultiBlockPLOT3DReader(
            xyz_file_name="temp/tvtk/plot3d_data/combxyz.bin",#网格文件
            q_file_name="temp/tvtk/plot3d_data/combq.bin",#空气动力学结果文件
            scalar_function_number=100,#设置标量数据数量
            vector_function_number=200#设置矢量数据数量
            )
    plot3d.update()
    return plot3d
 
plot3d = read_data()
grid = plot3d.output.get_block(0)

In [38]:
print(type(plot3d.output))

<class 'tvtk.tvtk_classes.multi_block_data_set.MultiBlockDataSet'>


In [39]:
print(type(plot3d.output.get_block(0)))

<class 'tvtk.tvtk_classes.structured_grid.StructuredGrid'>


In [40]:
print(grid.dimensions)

[57 33 25]


In [41]:
print(grid.points.to_array())

[[ 2.667     -3.77476   23.83292  ]
 [ 2.943465  -3.7482529 23.66556  ]
 [ 3.2198582 -3.7217531 23.49824  ]
 ...
 [15.84669    5.662141  35.74938  ]
 [16.178299   5.662141  35.74938  ]
 [16.51       5.662141  35.74938  ]]


In [42]:
print(grid.cell_data.number_of_arrays)

0


In [43]:
print(grid.point_data.number_of_arrays)

4


In [44]:
print(grid.point_data.scalars.name)

Density


In [46]:
print(grid.point_data.vectors.name)

Velocity
